# SPDX-License-Identifier: GPL-2.0-only
apple-isp-y := isp-cam.o isp-cmd.o isp-drv.o isp-fw.o isp-iommu.o isp-ipc.o isp-v4l2.o
obj-$(CONFIG_VIDEO_APPLE_ISP) += apple-isp.o
obj-$(CONFIG_VIDEO_APPLE_ISP_KUNIT_TEST) += isp-ipc-layout-test.o
