# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_APPLE_PMGR_PWRSTATE)	+= pmgr-pwrstate.o
obj-$(CONFIG_APPLE_PMGR_PWRSTATE)	+= gfx-tvm.o
obj-$(CONFIG_APPLE_PMP_REPORT)	+= pmp-report.o
obj-$(CONFIG_APPLE_PMP_REPORT_KUNIT_TEST) += pmp-report-test.o

obj-$(CONFIG_APPLE_PMC) += pmc.o
obj-$(CONFIG_APPLE_PMP_REPORT_NEO) += pmp-report-neo.o
